security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      database: ${MONGODB_DATABASE}
      uri: ${MONGODB_URI}

server:
  servlet:
    context-path: /accounts
  port: 6000

feign:
  hystrix:
    enabled: true